import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import gameReducer from "./ducks/game";
import { Provider } from "react-redux";
import { combineReducers, createStore } from "redux";
import Game from "./Components/Game";
const inter = Inter({ subsets: ["latin"] });

const rootReducer = combineReducers({
  game: gameReducer,
});
const store = createStore(rootReducer);

export default function Home() {
  return (
    <Provider store={store}>
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <Game></Game>
        </main>
      </>
    </Provider>
  );
}
