import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import gameReducer from "./ducks/game";
import { Provider } from "react-redux";
import { combineReducers, createStore } from "redux";
import Game from "./Components/Game";
import { useState } from "react";
const inter = Inter({ subsets: ["latin"] });
import startScreen from "../assets/startScreen.png";

const rootReducer = combineReducers({
  game: gameReducer,
});
const store = createStore(rootReducer);

export default function Home() {
  const [isGameStart, setIsGameStart] = useState(false);
  return (
    <Provider store={store}>
      <>
        <Head>
          <title>Coots Advenru</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" type="image/png" href="/icon.png" />
        </Head>
        <main className={styles.main}>
          {isGameStart ? (
            <Game />
          ) : (
            <div className={styles.mainContainer}>
              <div className={styles.imgContainer}>
                <img src={startScreen.src} alt="start screen img" />
              </div>
              <div className={styles.btnContainer}>
                <span
                  onClick={() => {
                    setIsGameStart(true);
                  }}
                >
                  Start Game
                </span>
              </div>
              <div>
                Game Made For The{" "}
                <a href="https://itch.io/jam/ludwig-2023">
                  Ludwig Game Jam 2023
                </a>{" "}
                By <a href="https://daviddodda.com">David Dodda</a> <br />{" "}
                {/* TODO  add github repo link*/}
                <br />{" "}
                <a href="https://github.com/daviddodda1/coots_adventures">
                  Project Github
                </a>
              </div>
            </div>
          )}
        </main>
      </>
    </Provider>
  );
}
